language: haskell
ghc: 7.8
script:
  - cabal configure --enable-tests --enable-coverage
  - cabal test --show-details=always --test-option=color
after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --exclude-dir=test hspec
env:
  global:
    secure: a16oCTxI7GBL+5j+pKkR4kghtOyErQCIJqNX1EHC5zxhWw5t4t1OQKhKUd+BFQxk6B7B+BQZ42549i4g9ESdCV7F8Se6DIFpj93a7uTtTeiPtnlxiiH2IVkWmvNVYswVk1uvBSnU7ZTJl8eG0GDPIlGtSvdBFWrXtHxO9W2pEXQ=
